#spring:
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    driver-class-name=com: mysql:jdbc:Driver
#    url: jdbc:mysql://mysql-database:3306/planetsapi?useSSL=false&allowPublicKeyRetrieval=true
#    username: user
#    password: password

spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver
springdoc:
  api-docs:
    path: /api-docs


